version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"        # location of pyproject.toml
    schedule:
      interval: "weekly"  # daily, weekly, or monthly
    open-pull-requests-limit: 10
    reviewers:
      - "birrgrrim"
    assignees:
      - "birrgrrim"
