name: Integration Tests CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install deps
        run: uv pip install --system -e .[dev]

      - name: Run integration tests
        run: pytest tests/integration -v
