name: Unit Tests CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install deps
        run: uv pip install --system -e .[dev]

      - name: Run unit tests
        run: pytest tests/unit -v
